debug: false

checkUpdate: true

data_storage:
  type: sqlite # sqlite or mysql
  # 数据库 KEY 模式 高版本、正版服建议 UUID
  keyModule: UUID
  mysql:
    host: '127.0.0.1'
    port: 3306
    database: 'server_reward'
    username: 'root'
    password: 'liao17303069590'
    params: '?autoReconnect=true&useSSL=false'
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000


状态信息:
  已领取: '&a已领取'
  可领取: '&a可领取'
  不可领取: '&c不可领取'
set:
  # 是否关闭 点券 的自动累计 （如果关闭 则需要管理员手动给与累计计数）
  closePoints: false
  # 是否关闭 金币 的自动累计 （如果关闭 则需要管理员手动给与累计计数）
  closeMoney: false
  # 是否关闭 在线时间 的自动累计 （如果关闭 则需要管理员手动给与累计计数）
  closeTime: false
  # 是否将在线时间设置为每日重置，如果填写 false 则是永久累计
  timeReset: true
  # 排行榜更新间隔 (秒)
  boardTime: 600